<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehicleSeeder extends Seeder
{
    public function run()
    {
        // Insert 15 vehicles
        DB::table('vehicles')->insert([
            [
                'rental_company_id' => null,  
                'owner_type' => 'company',
                'vehicle_type' => 'passenger',
                'license_plate' => 'B1234XYZ',
                'brand' => 'Toyota',
                'model' => 'Avanza',
                'year' => 2020,
                'fuel_type' => 'gasoline',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => 2,  
                'owner_type' => 'rental',
                'vehicle_type' => 'cargo',
                'license_plate' => 'D5678ABC',
                'brand' => 'Isuzu',
                'model' => 'Elf',
                'year' => 2018,
                'fuel_type' => 'diesel',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => 3,  
                'owner_type' => 'rental',
                'vehicle_type' => 'passenger',
                'license_plate' => 'A1234BCD',
                'brand' => 'Honda',
                'model' => 'Civic',
                'year' => 2021,
                'fuel_type' => 'gasoline',
                'status' => 'maintenance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => 4, 
                'owner_type' => 'rental',
                'vehicle_type' => 'passenger',
                'license_plate' => 'E9876FGH',
                'brand' => 'BMW',
                'model' => 'X5',
                'year' => 2019,
                'fuel_type' => 'gasoline',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => 5,  
                'owner_type' => 'rental',
                'vehicle_type' => 'cargo',
                'license_plate' => 'F1234IJK',
                'brand' => 'Mercedes-Benz',
                'model' => 'Sprinter',
                'year' => 2020,
                'fuel_type' => 'diesel',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => 1,  
                'owner_type' => 'rental',
                'vehicle_type' => 'passenger',
                'license_plate' => 'G2345LMN',
                'brand' => 'Kia',
                'model' => 'Seltos',
                'year' => 2022,
                'fuel_type' => 'gasoline',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => null,  
                'owner_type' => 'company',
                'vehicle_type' => 'cargo',
                'license_plate' => 'H5678OPQ',
                'brand' => 'Toyota',
                'model' => 'Hiace',
                'year' => 2021,
                'fuel_type' => 'diesel',
                'status' => 'maintenance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => 3,  
                'owner_type' => 'rental',
                'vehicle_type' => 'passenger',
                'license_plate' => 'J3456RST',
                'brand' => 'Nissan',
                'model' => 'X-Trail',
                'year' => 2020,
                'fuel_type' => 'hybrid',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => 4, 
                'owner_type' => 'rental',
                'vehicle_type' => 'cargo',
                'license_plate' => 'K9876UVW',
                'brand' => 'Ford',
                'model' => 'Ranger',
                'year' => 2018,
                'fuel_type' => 'diesel',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => 5,  
                'owner_type' => 'rental',
                'vehicle_type' => 'passenger',
                'license_plate' => 'L1234XYZ',
                'brand' => 'Suzuki',
                'model' => 'Ertiga',
                'year' => 2021,
                'fuel_type' => 'gasoline',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => 1,  
                'owner_type' => 'rental',
                'vehicle_type' => 'passenger',
                'license_plate' => 'M2345AAA',
                'brand' => 'Hyundai',
                'model' => 'Tucson',
                'year' => 2022,
                'fuel_type' => 'electric',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => 2,  
                'owner_type' => 'rental',
                'vehicle_type' => 'cargo',
                'license_plate' => 'N3456BBB',
                'brand' => 'Hino',
                'model' => '300 Series',
                'year' => 2019,
                'fuel_type' => 'diesel',
                'status' => 'maintenance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => null,  
                'owner_type' => 'company',
                'vehicle_type' => 'passenger',
                'license_plate' => 'O4567CCC',
                'brand' => 'Mazda',
                'model' => 'CX-5',
                'year' => 2021,
                'fuel_type' => 'gasoline',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => null, 
                'owner_type' => 'company',
                'vehicle_type' => 'cargo',
                'license_plate' => 'P5678DDD',
                'brand' => 'Chevrolet',
                'model' => 'Colorado',
                'year' => 2020,
                'fuel_type' => 'diesel',
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'rental_company_id' => null,  
                'owner_type' => 'company',
                'vehicle_type' => 'passenger',
                'license_plate' => 'Q6789EEE',
                'brand' => 'Mitsubishi',
                'model' => 'Outlander',
                'year' => 2019,
                'fuel_type' => 'gasoline',
                'status' => 'maintenance',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
